Repository pixiv/three-vrm, pull requests merged in 2020-10, with the labels that each got.

#500 feat (VRMBlendShapeProxy): Add a property, unknownGroupNames
  src/vrm/blendshape/VRMBlendShapeProxy.ts
Labels: enhancement

#507 fix (humanoid): getPose / setPose is now working as intended
  src/vrm/humanoid/VRMHumanoid.ts
Labels: Breaking Change, bug

#510 Deps: Bump several dependencies
  .eslintrc.json
  package.json
  src/vrm/lookat/VRMLookAtHead.ts
  src/vrm/material/MToonMaterial.ts
  src/vrm/material/VRMUnlitMaterial.ts
  src/vrm/springbone/VRMSpringBone.ts
  yarn.lock
Labels: dependencies

#501 refactor: Utilize generics of Mesh and SkinnedMesh
  src/vrm/firstperson/VRMFirstPerson.ts
  src/vrm/material/VRMMaterialImporter.ts
  src/vrm/types/types.ts
Labels: Refactor

#511 Add OffscreenCanvas support for extractThumbnailBlob
  src/vrm/VRMUtils/extractThumbnailBlob.ts
Labels: enhancement
