Repository pixiv/three-vrm, pull requests merged in 2020-09, with the labels that each got.

#478 VRMSpringBone: introducing center
  src/vrm/debug/VRMSpringBoneDebug.ts
  src/vrm/debug/VRMSpringBoneImporterDebug.ts
  src/vrm/springbone/VRMSpringBone.ts
  src/vrm/springbone/VRMSpringBoneImporter.ts
  src/vrm/springbone/VRMSpringBoneManager.ts
  src/vrm/utils/Matrix4WithInverseCache.ts
Labels: API Breaking, enhancement

#481 refactor (VRMSpringBone): Make most of constructor parameters an interface / make readonly parameters mutable
  src/vrm/debug/VRMSpringBoneDebug.ts
  src/vrm/debug/VRMSpringBoneImporterDebug.ts
  src/vrm/springbone/VRMSpringBone.ts
  src/vrm/springbone/VRMSpringBoneImporter.ts
  src/vrm/springbone/VRMSpringBoneParameters.ts
  src/vrm/springbone/index.ts
Labels: Breaking Change, Refactor

#482 Introducing VRMMeta, has an ability to load its thumbnail texture
  examples/meta.html
  src/vrm/VRM.ts
  src/vrm/VRMImporter.ts
  src/vrm/VRMUtils/extractThumbnailBlob.ts
  src/vrm/VRMUtils/index.ts
  src/vrm/meta/VRMMeta.ts
  src/vrm/meta/VRMMetaImporter.ts
  src/vrm/meta/VRMMetaImporterOptions.ts
Labels: Breaking Change, enhancement

#483 refactor: utilizing optional chaining and nullish coalescing
  src/vrm/blendshape/VRMBlendShapeImporter.ts
  src/vrm/blendshape/VRMBlendShapeProxy.ts
  src/vrm/debug/VRMLookAtImporterDebug.ts
  src/vrm/debug/VRMSpringBoneImporterDebug.ts
  src/vrm/firstperson/VRMFirstPersonImporter.ts
  src/vrm/humanoid/VRMHumanoid.ts
  src/vrm/humanoid/VRMHumanoidImporter.ts
  src/vrm/lookat/VRMLookAtImporter.ts
  src/vrm/material/VRMMaterialImporter.ts
  src/vrm/utils/disposer.ts
Labels: Refactor

#485 fix (VRMUtils.extractThumbnailBlob): forgot to unassign the texture
  src/vrm/VRMUtils/extractThumbnailBlob.ts
Labels: bug

#486 fix (VRMMeta): expose VRMMeta
  src/vrm/index.ts
  src/vrm/meta/index.ts
Labels: bug

#487 refactor (VRMSpringBone): A better way to cache the inverse of the world matrix
  src/vrm/springbone/VRMSpringBone.ts
  src/vrm/utils/Matrix4InverseCache.ts
  src/vrm/utils/Matrix4WithInverseCache.ts
Labels: Refactor

#488 bump three.js to 0.120.1
  examples/animations.html
  examples/basic.html
  examples/blendshapes.html
  examples/bones.html
  examples/debug.html
  examples/dnd.html
  examples/encoding.html
  examples/envmap.html
  examples/firstperson.html
  examples/lookat-advanced.html
  examples/lookat.html
  examples/materials-debug.html
  examples/meta.html
  examples/mouse.html
  package.json
  yarn.lock
Labels: dependencies

#489 `VRMBlendShapeProxy._blendShapeGroups` was unintentionally public
  src/vrm/blendshape/VRMBlendShapeProxy.ts
Labels: bug

#497 fix (VRMImporterDebug): MetaImporter was not used, fixing this
  src/vrm/debug/VRMImporterDebug.ts
Labels: bug

#498 add getter for presetNameMap
  src/vrm/blendshape/VRMBlendShapeProxy.ts
Labels: enhancement
