Repository pixiv/three-vrm, pull requests merged in 2024-05, with the labels that each got.

#1399 deps: Bump Three.js and its type definition to r164
  packages/three-vrm-animation/package.json
  packages/three-vrm-core/package.json
  packages/three-vrm-materials-hdr-emissive-multiplier/package.json
  packages/three-vrm-materials-mtoon/package.json
  packages/three-vrm-materials-v0compat/package.json
  packages/three-vrm-node-constraint/package.json
  packages/three-vrm-springbone/package.json
  packages/three-vrm/package.json
  yarn.lock
Labels: dependencies

#1402 fix: MToon, Fix uv animation transform order
  packages/three-vrm-materials-mtoon/src/shaders/mtoon.frag
Labels: bug

#1404 fix: Fix MToon default parameters
  packages/three-vrm-materials-mtoon/src/MToonMaterial.ts
Labels: bug

#1407 fix: Fill default MToon parameters for v0 VRMs
  packages/three-vrm-materials-v0compat/src/VRMMaterialsV0CompatPlugin.ts
Labels: bug

#1406 feat: typescript v5
  .eslintrc.json
  package.json
  packages/three-vrm-materials-mtoon/src/utils/getTextureColorSpace.ts
  packages/three-vrm-materials-mtoon/src/utils/setTextureColorSpace.ts
  yarn.lock
Labels: dependencies

#1410 fix: MToon, Fix normal mapping when other textures are not specified
  packages/three-vrm-materials-mtoon/src/MToonMaterial.ts
Labels: bug

#1411 BREAKING: feat: migrate to esbuild
  .eslintrc.json
  .gitignore
  bin/build.mjs
  jest.config.js
  jest.config.mjs
  package.json
  packages/three-vrm-animation/package.json
  packages/three-vrm-animation/rollup.config.js
  packages/three-vrm-core/jest.config.js
  packages/three-vrm-core/jest.config.mjs
  packages/three-vrm-core/package.json
  packages/three-vrm-core/rollup.config.js
  packages/three-vrm-materials-hdr-emissive-multiplier/package.json
  packages/three-vrm-materials-hdr-emissive-multiplier/rollup.config.js
  packages/three-vrm-materials-mtoon/package.json
  packages/three-vrm-materials-mtoon/rollup.config.js
  packages/three-vrm-materials-v0compat/package.json
  packages/three-vrm-materials-v0compat/rollup.config.js
  packages/three-vrm-node-constraint/jest.config.js
  packages/three-vrm-node-constraint/jest.config.mjs
  packages/three-vrm-node-constraint/package.json
  packages/three-vrm-node-constraint/rollup.config.js
  packages/three-vrm-springbone/jest.config.js
  packages/three-vrm-springbone/jest.config.mjs
  packages/three-vrm-springbone/package.json
  packages/three-vrm-springbone/rollup.config.js
  packages/three-vrm/package.json
  packages/three-vrm/rollup.config.js
  tsconfig.json
  yarn.lock
Labels: Breaking Change, dependencies

#1413 Fix leftover rollup stuff
  package.json
  packages/three-vrm-animation/package.json
  packages/three-vrm-core/package.json
  packages/three-vrm-materials-hdr-emissive-multiplier/package.json
  packages/three-vrm-materials-mtoon/package.json
  packages/three-vrm-materials-v0compat/package.json
  packages/three-vrm-node-constraint/package.json
  packages/three-vrm-springbone/package.json
  packages/three-vrm/package.json
  yarn.lock
Labels: dependencies

#1415 BREAKING: fix: default needThumbnailImage to false
  packages/three-vrm-core/src/meta/VRMMetaLoaderPlugin.ts
  packages/three-vrm-core/src/meta/VRMMetaLoaderPluginOptions.ts
Labels: Breaking Change

#1384 BREAKING: WebGPU support (MToonNodeMaterial)
  packages/three-vrm-materials-mtoon/examples/index.html
  packages/three-vrm-materials-mtoon/examples/webgpu-feature-test.html
  packages/three-vrm-materials-mtoon/examples/webgpu-loader-plugin.html
  packages/three-vrm-materials-mtoon/src/MToonMaterialLoaderPlugin.ts
  packages/three-vrm-materials-mtoon/src/index.ts
  packages/three-vrm-materials-mtoon/src/nodes/MToonAnimatedUVNode.ts
  packages/three-vrm-materials-mtoon/src/nodes/MToonLightingModel.ts
  packages/three-vrm-materials-mtoon/src/nodes/MToonNodeMaterial.ts
  packages/three-vrm-materials-mtoon/src/nodes/MToonNodeMaterialLoaderPlugin.ts
  packages/three-vrm-materials-mtoon/src/nodes/MToonNodeMaterialParameters.ts
  packages/three-vrm-materials-mtoon/src/nodes/immutableNodes.ts
  packages/three-vrm-materials-mtoon/src/nodes/index.ts
  packages/three-vrm-materials-mtoon/src/nodes/materialReferences.ts
  packages/three-vrm-materials-mtoon/src/nodes/mtoonParametricRim.ts
  packages/three-vrm/examples/index.html
  packages/three-vrm/examples/webgpu-dnd.html
  packages/three-vrm/src/VRMUtils/removeUnnecessaryJoints.ts
  tsconfig.json
Labels: enhancement, Breaking Change
