Repository pixiv/three-vrm, pull requests merged in 2024-01, with the labels that each got.

#1348 deps: Bump three to r160
  README.md
  packages/three-vrm-core/examples/expressions.html
  packages/three-vrm-core/examples/firstPerson.html
  packages/three-vrm-core/examples/humanoid.html
  packages/three-vrm-core/examples/humanoidAnimation/index.html
  packages/three-vrm-core/examples/humanoidAnimation/main.js
  packages/three-vrm-core/examples/lookAt.html
  packages/three-vrm-core/examples/meta.html
  packages/three-vrm-core/package.json
  packages/three-vrm-materials-hdr-emissive-multiplier/examples/loader-plugin.html
  packages/three-vrm-materials-hdr-emissive-multiplier/package.json
  packages/three-vrm-materials-mtoon/examples/emissive-strength.html
  packages/three-vrm-materials-mtoon/examples/feature-test.html
  packages/three-vrm-materials-mtoon/examples/loader-plugin.html
  packages/three-vrm-materials-mtoon/package.json
  packages/three-vrm-materials-mtoon/src/MToonMaterial.ts
  packages/three-vrm-materials-mtoon/src/shaders/mtoon.frag
  packages/three-vrm-materials-v0compat/package.json
  packages/three-vrm-node-constraint/examples/aim.html
  packages/three-vrm-node-constraint/examples/importer.html
  packages/three-vrm-node-constraint/examples/roll.html
  packages/three-vrm-node-constraint/examples/rotation.html
  packages/three-vrm-node-constraint/examples/upper-arm.html
  packages/three-vrm-node-constraint/package.json
  packages/three-vrm-node-constraint/src/VRMAimConstraint.ts
  packages/three-vrm-node-constraint/src/VRMRollConstraint.ts
  packages/three-vrm-node-constraint/src/VRMRotationConstraint.ts
  packages/three-vrm-node-constraint/src/tests/VRMMockedConstraint.ts
  packages/three-vrm-springbone/examples/collider.html
  packages/three-vrm-springbone/examples/loader-plugin.html
  packages/three-vrm-springbone/examples/multiple.html
  packages/three-vrm-springbone/examples/single.html
  packages/three-vrm-springbone/package.json
  packages/three-vrm/README.md
  packages/three-vrm/examples/animations.html
  packages/three-vrm/examples/basic.html
  packages/three-vrm/examples/bones.html
  packages/three-vrm/examples/debug.html
  packages/three-vrm/examples/dnd.html
  packages/three-vrm/examples/expressions.html
  packages/three-vrm/examples/firstperson.html
  packages/three-vrm/examples/humanoidAnimation/index.html
  packages/three-vrm/examples/humanoidAnimation/main.js
  packages/three-vrm/examples/lookat-advanced.html
  packages/three-vrm/examples/lookat.html
  packages/three-vrm/examples/materials-debug.html
  packages/three-vrm/examples/meta.html
  packages/three-vrm/examples/mouse.html
  packages/three-vrm/package.json
  yarn.lock
Labels: dependencies

#1353 fix: Normalized bones now respect non humanoid parent rotations
  packages/three-vrm-core/src/humanoid/VRMHumanoidRig.ts
Labels: bug

#1359 Remove `.needsUpdate` after texture transforms
  packages/three-vrm-core/src/expressions/VRMExpressionTextureTransformBind.ts
Labels: performance
