Repository pixiv/three-vrm, pull requests merged in 2024-08, with the labels that each got.

#1459 docs: Update README examples
  README.md
  packages/three-vrm-materials-mtoon/README.md
  packages/three-vrm/README.md
Labels: documentation

#1455 Fix humanoidAnimation example
  packages/three-vrm/examples/humanoidAnimation/main.js
Labels: examples

#1448 Feature: support `VRMC_springBone_extended_collider`
  .github/workflows/inspect.yml
  packages/three-vrm-springbone/examples/index.html
  packages/three-vrm-springbone/examples/inside-collider.html
  packages/three-vrm-springbone/examples/loader-plugin.html
  packages/three-vrm-springbone/examples/models/cube_mesh.bin
  packages/three-vrm-springbone/examples/models/inside-collider.gltf
  packages/three-vrm-springbone/examples/models/plane-collider.gltf
  packages/three-vrm-springbone/examples/models/plane_mesh.bin
  packages/three-vrm-springbone/examples/models/sphere-collider.gltf
  packages/three-vrm-springbone/examples/models/sphere_mesh.bin
  packages/three-vrm-springbone/examples/plane-collider.html
  packages/three-vrm-springbone/package.json
  packages/three-vrm-springbone/src/VRMSpringBoneColliderShapeCapsule.ts
  packages/three-vrm-springbone/src/VRMSpringBoneColliderShapePlane.ts
  packages/three-vrm-springbone/src/VRMSpringBoneColliderShapeSphere.ts
  packages/three-vrm-springbone/src/VRMSpringBoneLoaderPlugin.ts
  packages/three-vrm-springbone/src/VRMSpringBoneLoaderPluginOptions.ts
  packages/three-vrm-springbone/src/helpers/VRMSpringBoneColliderHelper.ts
  packages/three-vrm-springbone/src/helpers/utils/ColliderShapePlaneBufferGeometry.ts
  packages/three-vrm-springbone/src/index.ts
  packages/types-vrmc-springbone-extended-collider-1.0/.gitignore
  packages/types-vrmc-springbone-extended-collider-1.0/README.md
  packages/types-vrmc-springbone-extended-collider-1.0/package.json
  packages/types-vrmc-springbone-extended-collider-1.0/tsconfig.json
  packages/types-vrmc-springbone-extended-collider-1.0/types/SpringBoneExtendedColliderShape.d.ts
  packages/types-vrmc-springbone-extended-collider-1.0/types/SpringBoneExtendedColliderShapeCapsule.d.ts
  packages/types-vrmc-springbone-extended-collider-1.0/types/SpringBoneExtendedColliderShapePlane.d.ts
  packages/types-vrmc-springbone-extended-collider-1.0/types/SpringBoneExtendedColliderShapeSphere.d.ts
  packages/types-vrmc-springbone-extended-collider-1.0/types/VRMCSpringBoneExtendedCollider.d.ts
  packages/types-vrmc-springbone-extended-collider-1.0/types/index.d.ts
Labels: enhancement

#1460 examples: Fix jsdelivr three-vrm version on three-vrm-animation examples
  packages/three-vrm-animation/examples/dnd.html
  packages/three-vrm-animation/examples/loader-plugin.html
Labels: examples

#1449 feat: VRMAnimation, emit a warning if the rest hips potision is approximately zero
  packages/three-vrm-animation/src/VRMAnimationLoaderPlugin.ts
Labels: enhancement

#1468 deps: Bump husky to v9
  .husky/.gitignore
  .husky/pre-commit
  .husky/pre-push
  package.json
  yarn.lock
Labels: dependencies

#1470 deps: Bump prettier to v3.3.3
  package.json
  packages/three-vrm-core/src/expressions/VRMExpressionMaterialColorType.ts
  packages/three-vrm-core/src/expressions/VRMExpressionOverrideType.ts
  packages/three-vrm-core/src/expressions/VRMExpressionPresetName.ts
  packages/three-vrm-core/src/firstPerson/VRMFirstPersonMeshAnnotationType.ts
  packages/three-vrm-core/src/humanoid/VRMHumanBoneName.ts
  packages/three-vrm-core/src/humanoid/VRMRequiredHumanBoneName.ts
  packages/three-vrm-core/src/lookAt/VRMLookAtTypeName.ts
  packages/three-vrm-materials-mtoon/src/MToonMaterialDebugMode.ts
  packages/three-vrm-materials-mtoon/src/MToonMaterialOutlineWidthMode.ts
  packages/three-vrm-materials-v0compat/src/VRMMaterialsV0CompatPlugin.ts
  yarn.lock
Labels: dependencies, Refactor

#1472 deps: Bump lerna from v6.6.2 to v8.1.8
  .prettierignore
  lerna.json
  package.json
  tsconfig.json
  yarn.lock
Labels: dependencies
